global:
  training_locally_bool: False

data_pipeline:
  local_filepath: D:\Data\
  cloud_filepath: /home/ubuntu/Data/

model_artifact_filepath:
    local_callbacks: D:\model_artifacts\callbacks
    cloud_callbacks: /home/ubuntu/model_artifacts/callbacks
    local_artifacts: D:\model_artifacts\
    cloud_artifacts: /home/ubuntu/model_artifacts/


data_collection:
  target_website: https://this-person-does-not-exist.com/en
  fake_image_dir: ../data/fake_people
  chromedriver_location: utils/chromedriver.exe
  attribute_to_retreive: avatar
  element_id: src
  scraping_attempts: 10000
  total_needed_fake_images: 60000

model_inference:
  saved_model_location: ../api
  best_model_name: best_model.hdf5 

model_training:
  model_params: 
    first_filter: [32, 30, 25, 10] 
    first_kernel: [5, 3] 
    second_filter: [32, 30, 25, 10]     
    second_kernel: [3]
    third_filter: [16, 12, 9]     
    third_kernel: [3]
    batch_size: [200]
    beta_1: [0.6, 0.63, 0.66]
    pooling: [layers.MaxPool2D, layers.AvgPool2D]
    dense_nodes: [32, 24, 16]
    learning_rate: [0.01, 0.001, 0.002]
    regularization: [[True, 0.001, 0.30], [True, 0.002, 0.40], [False, 0.001, 0.30], [True, 0.002, 0.40]]
    img_size: [200]
    max_epochs: 100


    